### ISSUE TITLE
Anzeige der Leistung Eingang 2 nicht korrekt

### ISSUE THREAD

**Issue by maliblatt** [ngrie/powerinterface#1]
Hallo!
Im Webinterface sehe ich als Leistung für den Eingang 2 immer exakt den Wert von Eingang 1. Beim Abgleich mit den Werten auf mypowerrouter.com scheint es so, als würde die Leistung am Eingang 2 tatsächlich nicht korrekt angezeigt.
Lässt sich das korrigieren?
Danke!!
![1](https://user-images.githubusercontent.com/5854684/105576347-68bffe80-5d72-11eb-8767-2a5af77e7d12.png)
![2](https://user-images.githubusercontent.com/5854684/105576348-6b225880-5d72-11eb-867c-27b64a99e16d.png)

**Comment by maliblatt** [comment]
Ich denke, in der Zeile hier liegt das Problem:
https://github.com/ngrie/powerinterface/blob/78fad3236d14c03ef0187158a1f52d3a747d2f27/src/webinterface.js#L45
Dort müsste wohl data.line2Power rein ...

**Comment by ngrie** [comment]
Hi,

good catch! Ich habe das gerade korrigiert, mit dem Update sollte der Wert nun richtig angezeigt werden. Danke fürs Melden!
Und schön, dass die Installation anscheinend gut funktioniert hat (und das obwohl es noch keine Anleitung gibt ...).
