### ISSUE TITLE
Fehler beim Start als Service

### ISSUE THREAD

**Issue by Tenner** [ngrie/powerinterface#7]
Hi Ngrie,
ich hoffe du kannst mir weiterhelfen. Inspiriert vom Heimbauprojekt, dass Powerinterface auf einem Raspi laufen zu haben, wollte ich das ganze auf deiner Diskstation realisieren. 

Nun fehlt als letzter Schritt das Powerinterface als Service einzurichten. Hier bekomme ich folgende Fehlermeldung..
em@mypowerrouter:/srv/powerinterface$ journalctl _PID=16203
-- Logs begin at Mon 2021-06-14 09:00:39 CEST, end at Mon 2021-06-14 13:51:31 CEST. --
Jun 14 13:49:59 mypowerrouter node[16203]: /srv/powerinterface/server.js:1
Jun 14 13:49:59 mypowerrouter node[16203]: import fs from 'fs'
Jun 14 13:49:59 mypowerrouter node[16203]:        ^^
Jun 14 13:49:59 mypowerrouter node[16203]: SyntaxError: Unexpected identifier
Jun 14 13:49:59 mypowerrouter node[16203]:     at Module._compile (internal/modules/cjs/loader.js:723:23)
Jun 14 13:49:59 mypowerrouter node[16203]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js>
Jun 14 13:49:59 mypowerrouter node[16203]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Jun 14 13:49:59 mypowerrouter node[16203]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Jun 14 13:49:59 mypowerrouter node[16203]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Jun 14 13:49:59 mypowerrouter node[16203]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:1>
Jun 14 13:49:59 mypowerrouter node[16203]:     at startup (internal/bootstrap/node.js:283:19)
Jun 14 13:49:59 mypowerrouter node[16203]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Ich hoffe du kannst mir weiterhelfen.

**Comment by ngrie** [comment]
Ohne nähere Details zu deinem Setup und den durchgeführten Installationsschritten kann ich nur Vermutungen anstellen: Möglicherweise ist die verwendete NodeJS zu alt. Funktionieren sollte es mit v13 oder höher. Was sagt `node -v`?

**Comment by Tenner** [comment]
Haha, da steht v10.19.0. Ich schau mal wie ich die updaten kann...
Mit curl -sSL https://deb.nodesource.com/setup_14.x | sudo bash -
wirft der mir eine seltsame Meldung und macht nicht weiter ;(

**Comment by Tenner** [comment]
Es war wohl irgendeine Paketquelle kaputt, ich glaube die Installation läuft jetzt. Melde mich ;)

**Comment by Tenner** [comment]
Das war es. Herzlichen Dank ;)
